from typing import Callable, Protocol


class AudioIO(Protocol):
    def start_input(self, callback: Callable[[bytes], None]) -> None: ...
    def stop_input(self) -> None: ...
    def play(self, pcm: bytes) -> None: ...
    def set_capture_enabled(self, enabled: bool) -> None: ...
